### ISSUE TITLE
Homey-Arduino missing

### ISSUE THREAD

**Issue by rhannink** [athombv/com.athom.homeyduino#1]
Hello,
When I do a **git clone** and install the app on my Homey, the app directly crashes. It looks like the **homey-arduino** node.js modules are not in their place. There's an empty **homey-arduino** dir under **node_modules**.

Gr. Remco

**Comment by mruiter** [comment]
yes you can get that from git also and combine. This is by design 😜

so you can close this issue now

**Comment by renzenicolai** [comment]
try "git clone --recursive". The homey-arduino node.js library is included as a GIT submodule.
