### ISSUE TITLE
RC is not working with ESP8266

### ISSUE THREAD

**Issue by AlbertDijksma** [athombv/com.athom.homeyduino#29]
Your board is of an unknown type. Please send us the following information in a Github issue to allow us to add support for your board:

Board architecture	esp8266
Amount of digital pins	17
Anount of analog inputs	1

Je mag dit venster sluiten.

{"id":"RCtest","version":"0.9.6","type":"homeyduino","class":"other","rc":{"arch":"esp8266","numDigitalPins":17,"numAnalogInputs":1},"master":{"host":"192.168.8.183", "port":42329},"api":[{"name":"mode", "type":"rc"},{"name":"dwrite", "type":"rc"},{"name":"dread", "type":"rc"},{"name":"awrite", "type":"rc"},{"name":"aread", "type":"rc"}]}

**Comment by AlbertDijksma** [comment]
I found an issue in the boards.json.
for ESP8266 and ESP32 the numAnalogPins must be numAnalogInputs,

**Comment by renzenicolai** [comment]
(should be fixed, if not please reopen the issue)
