### ISSUE TITLE
RC is not working with ESP32

### ISSUE THREAD

**Issue by AlbertDijksma** [athombv/com.athom.homeyduino#30]
Your board is of an unknown type. Please send us the following information in a Github issue to allow us to add support for your board:

Board architecture	esp32
Amount of digital pins	40
Anount of analog inputs	16

Je mag dit venster sluiten.

**Comment by AlbertDijksma** [comment]
I found an issue in the boards.json.
for ESP8266 and ESP32 the numAnalogPins must be numAnalogInputs,

**Comment by jeroenvollenbrock** [comment]
Closing as duplicate of #29
