### ISSUE TITLE
ESP32 RC folder missing!

### ISSUE THREAD

**Issue by rhannink** [athombv/com.athom.homeyduino#31]
Hello,

Just compiled the RC example to an ESP32 (DoIT ESP32 DEV) everything is ok, Homey finds the module and detects it as an ESP32. But when I choose the exact type, an error occurs. It looks like the entire **ESP32** folder under **pair/RC** is missing. There's only an **ESP8266**, a **SAM** and an **AVR** folder there.

**Comment by renzenicolai** [comment]
That folder doesn't exist (yet) as basic support for the esp32 targets is still showing problems.
(TCP packets are sometimes not received correctly, causing connection issues)

I don't have a DoIT board available to test with, but feel free to add board definitions for the boards that you want to use and create a pull request.

**Comment by renzenicolai** [comment]
(should be solved, please reopen if problem still exists)
