### ISSUE TITLE
Trying to get the 'Remote configuration' to get to work in a Homey flow

### ISSUE THREAD

**Issue by 2mvent** [athombv/com.athom.homeyduino#40]
Hi,
I'm trying to get the 'Remote configuration' to get to work in a Homey flow but now I am stuck at the flow card in Homey.

I do not get any reading to or from that flow card.
![image](https://user-images.githubusercontent.com/31533211/34649618-2eddf158-f3b3-11e7-96ad-ea0644434c1a.png)

What I am trying to do is to get Homey to interact with a NodeMCU to switch a relay on and off.

What I have done so far is:
Bought a NodeMCU V3 (https://nl.aliexpress.com/item/ESP8266-CH340G-CH340-G-NodeMcu-V3-Lua-Wireless-WIFI-Module-Connector-Development-Board-Based-ESP-12E/32800966224.html)
and a relay, connected those together and installed Arduino 1.8.5 IDE.
Installed the NodeMCu library: http://arduino.esp8266.com/stable/package_esp8266com_index.json

Uploaded the sketch:
```
void setup() {
  // initialize digital pin 13 as an output.
  pinMode(12, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(12, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(2000);              // wait for a second
  digitalWrite(12, LOW);    // turn the LED off by making the voltage LOW
  delay(2000);              // wait for a second
}
```
And tried all the pinMode 01, 04, 00, 02, 14, 12, 13 and 15 to get the D1 to D8 to switch the relay on and off. This all worked.

So I installed the Homeyduino in Homey
and downloaded the zip homey-arduino-library-master.zip and installed it .
Uploaded the esp8266.ino (the one from homey-arduino-library-master\examples\Remote configuration\esp8266\esp8266.ino and changed the ssid pass and id)

In Homey I can add a device homeyduino device select 'NodeMCU 1.0 V2' and assign 'digital input' 'digital output' 'digital input with triggers' to D1 and so forth.

But then I get to a flow and I do not know what to do with that flowcard?
Where can I find what to do with that flowcard?

I'm stuck. How do I proceed?

Best regards, Herbert

**Comment by renzenicolai** [comment]
I've tried to reproduce the bug you describe but everything seems to work.

What I did:
 - I opened the esp8266 remote configuration sketch and changed the SSID, PASS and ID variables. Otherwise I made no changes to the file.
 - I selected the board type to be "NodeMCU 1.0 (ESP12E)" in the Arduino IDE.
 - I uploaded the sketch to the NodeMCU board
 - I paired with the device on Homey and selected the "NodeMCU 1.0" board option, I selected D0, D1 and D2 to be "digital output" and left the rest on "digital input".

Now when I add the "Digital output: OFF" action to a flow the "pinD0", "pinD1" and "pinD2" options are available, as expected.

Please try again using the steps described above. If the problem still exists please let me know.

**Comment by brtwrs** [comment]
Hi! I have exactly the same problem as 2mvent. Pairing my esp goes perfect now but my flow cards don't  show any of the pins I defined during the pairing process. I used the remote config code in my esp12

**Comment by 2mvent** [comment]
Hi Renze,

So I did everything again and this time I took a screenshot of every step. But surprise: then the outcome was the expected results. (The one that you have)
I do not recall doing anything in between (with homey) when I posted the first post and doing it once again for this post.
Also, I did not do anything different the first time than you have done.

The 'bug' (you have to give a name to the phenomenon) is real. When you install en prepare arduino/esp8266 like you should, then you could end up with zero readings in a flow (after succesfully pairing it and assigning a digital output to some pins)

It reminds me of a problem I had with the opengateway app. I had to restart that app to get it working, but all things looked normal and I could select it and pair it as well, but than it gave no readings at all.
In the homeyduinos case, the app was just installed, and I do remember restarting it to see if that could set things in motion. But it didn't, at that time at least.

I am using Homey Firmware Versie: 1.5.6-rc.8

brtwrs: I could give you a suggestion to reboot the whole homey and see if that makes a difference in outcome. 

Best regards,
Herbert

**Comment by brtwrs** [comment]
Thanks for the suggestion! But it is still not working, still the "no results found..." message

**Comment by renzenicolai** [comment]
brtwrs: Please make sure that you're on the latest version of both the app (1.0.1) and the library (1.0.2), could you confirm that you have installed these versions of the software? In the Arduino IDE you can just select Homeyduino in the library manager, no need to download a zip from github anymore... The 1.0.1 app is the latest stable version on the app-store.

**Comment by renzenicolai** [comment]
2mvent: I will look into this next week. The app itself (without the remote configuration feature) is much more stable. Defining actions and triggers in an Arduino sketch should work flawlessly.

**Comment by brtwrs** [comment]
I'm using library 1.0.2 and app version 1.0.2 because of #41 you fixed. Could this be the problem?

**Comment by Asinke** [comment]
Hi Renze, sorry to say but it seems i have exactly the same issue as 2mvent initially and brtwrs.
I'm following the exact same procedure as you outlined, using a Wemos D1 mini (esp8266).
From the action flowcards, not a single digital input or output are selectable.

I'm running homeyduino 1.01 and the updated libraries from within the arduino ide.

Any ideas on where to look for the problem?

**Comment by brtwrs** [comment]
Any news on this issue?

**Comment by 2mvent** [comment]
Well, this problem is back!
I switched from one Nodemcu to another and now I have the same situation again.
So, after pairing there are zero readings in a homeduino flowcard.

I'm not all that familiar with the Arduino IDE, so I will ask a question without any knowledge:
Why is the 'HomeyRemoteConfiguration.h' grayed out, while the other #includes have a colorcoding:

![image](https://user-images.githubusercontent.com/31533211/36167118-094f3582-10f5-11e8-98d1-cdbc3093bfde.png)

If I google this color coding thing, it says that library that is grayed out is missing in your library.
Is this true?
If so, how do I include it?

**Comment by 2mvent** [comment]
@renzenicolai , 17 jan you tried to reproduce the 'bug' and it did not occur when you tried it.
Of course I understand it is difficult fixing things that you can not reproduce.
So I want to ask you, did you try to reproduce this phenomenon on your development machine?
If not, how did you try to reproduce this?

In my case I had a pristine PC win10 (installed it a few months ago, fully updated), and it did not have an arduino ide (1.8.5) installed before, let alone the esp8266 arduino package, and the homey-arduino-library-master.zip. The homey desktop was not installed before either.

Is this different then your test setup?

It would just be a pity seeing such efforts and in principle brilliant ideas, come to a complete full stop because you just can not use it.

If you would like other info, or if you want me to try something, just let me know.

**Comment by renzenicolai** [comment]
I am currently busy with my graduation internship, because of this I do not have time to look any further into the issue you are experiencing.

Could you try using Homeyduino without the remote configuration features and see if that works for you? Also you could try to run the Homeyduino app using Athoms CLI utility for development. That way you can see the log and check where things go wrong. 

Also note that the missing color of the header file you include is not an issue.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2594
