### ISSUE TITLE
Something went wrong while fetching or parsing the board information file for the board you selected. Can not continue.

### ISSUE THREAD

**Issue by brtwrs** [athombv/com.athom.homeyduino#41]
This project looks really interesting! Im able to compile the rc example and flash it. The homey app detects my esp but when I choose "generic esp8266" I get the following error:
Something went wrong while fetching or parsing the board information file for the board you selected. Can not continue.

I have a ESP12, does this devices needs te be added first?

Thanks!

**Comment by renzenicolai** [comment]
This sounds like a bug, I will look into this next monday.

**Comment by renzenicolai** [comment]
The issue was a missing comma in the JSON file describing the generic ESP8266 board option. This bug has been fixed in the current master version of Homeyduino. I do not yet know when the next appstore release will take place.

https://github.com/athombv/com.athom.homeyduino/pull/42
