### ISSUE TITLE
List of previous paired names still show in pairing wizard

### ISSUE THREAD

**Issue by IvoDerksen** [athombv/com.athom.homeyduino#43]
Can't delete them, maybe they are stored in the Homey app cache and could be cleared?

![image](https://user-images.githubusercontent.com/22196684/35123775-e66f9468-fca3-11e7-8862-dd7229bff34c.png)

Just a suggestion/enhancement

Good job on this awesome app!

**Comment by renzenicolai** [comment]
Keeping devices which do not immediately respond in the list was ment to work like this by design. After a while the devices should automatically disappear from the pairing list. If that is not the case please let me know!

**Comment by renzenicolai** [comment]
Apparently devices do not always disappear from the device list after they go offline for a defined amount of time. Could be a small bug...

**Comment by IvoDerksen** [comment]
But a restart does worked as described. So if it is of bother to anyone.
