### ISSUE TITLE
Unable to add device

### ISSUE THREAD

**Issue by Caros2017** [athombv/com.athom.homeyduino#8]
I'm running Homey version 1.5.3 and installed Homeyduino version 0.1.0.
When I want to add an Arduino in devices, I only see a wheel scrolling. Nothing else happens even if I wait for minutes. Unable to manually add something, since the wheel doesn't stop spinning... :) Only option I have is to click next.

**Comment by Caros2017** [comment]
@renzenicolai, Arduino is fine reachable through port 46639:
{"id":"esp8266example","type":"homeyduino","class":"other","arch":"esp8266","numDigitalPins":"17","numAnalogInputs":"1","rc":"0","master":{"host":"0.0.0.0", "port":9999},"api":{"0":{"name":"myaction", "type":"act"},"1":{"name":"mycondition", "type":"con"}}}

Anything else I can try to manually add the device? Can't get to this screen unfortunately.

**Comment by Caros2017** [comment]
@renzenicolai, I see you are busy working on this project. I've just update to v0.9.3. Unfortunately still only the spinning wheel and no possibility for adding the arduino manually. Looking forward to see this work, especially now I saw that even the Sonoff has been added (picture). Working on as wel a 'normal' arduino ESP2866 aswell as flashing a Sonoff.

**Comment by renzenicolai** [comment]
Could you please try using both the latest Arduino library and the latest app? If the problem still occurs then please contact me on Slack so we can figure out what is going wrong.

**Comment by AlbertDijksma** [comment]
Hi Renzenicolai,

I see the same problem as Caros2017.
Spinning wheel and no possibility for adding the arduino manually.
I’m running Homey at firmware 1.5.5, HomeyDuino 0.9.4 and the latest Arduino library.
I’m using homey with the Dutch language setting.

**Comment by AlbertDijksma** [comment]
It looks like an isue with the athom windows desktop app.
When i use the webrowser of my samsung tablet i see rhe possibility to assing the arduino manually

**Comment by renzenicolai** [comment]
This problem should be fixed in 0.9.6! (0.9.6 is now available as beta in the app store)
